# Generated by Django 5.1.3 on 2024-11-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], max_length=20)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
